# Generated by Django 5.2.3 on 2026-01-04 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booked_on']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hotelimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='country',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='-', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_nights',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_in_time',
            field=models.CharField(default='2:00 PM', max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_time',
            field=models.CharField(default='12:00 PM', max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='free_self_parking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='free_valet_parking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_breakfast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_parking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_pool',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_restaurant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_spa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_wifi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='min_check_in_age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='hotel',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='require_deposit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='require_id',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='smoking_area',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='special_checkin_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='wifi_speed',
            field=models.CharField(default='25+ Mbps', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='has_wifi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='refundable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(choices=[('Superior Twin', 'Superior Twin Room'), ('Premium', 'Premium Room'), ('Executive', 'Executive Room'), ('Deluxe', 'Deluxe Room'), ('Suite', 'Suite Room')], default='-', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='size_sq_m',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='room',
            name='sleeps',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='view_type',
            field=models.CharField(choices=[('City', 'City View'), ('River', 'River View'), ('Mountain', 'Mountain View'), ('Garden', 'Garden View'), ('Sea', 'Sea View')], default='City', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='h_app.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='h_app.room')),
            ],
        ),
    ]
