# Generated by Django 5.2.3 on 2026-01-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_app', '0002_alter_booking_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='also_known_as',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hotel',
            name='breakfast_price_adult',
            field=models.PositiveIntegerField(default=499, help_text='Breakfast price for adults (INR)'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='breakfast_price_child',
            field=models.PositiveIntegerField(default=349, help_text='Breakfast price for children (INR)'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='policies',
            field=models.TextField(blank=True, help_text='Enter one policy per line'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='pool_timings',
            field=models.CharField(default='6:00 AM – 6:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='refundable_deposit',
            field=models.PositiveIntegerField(default=2000, help_text='Deposit per stay (INR)'),
        ),
    ]
