# Generated by Django 5.2.3 on 2026-01-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_app', '0003_hotel_also_known_as_hotel_breakfast_price_adult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='gst_percent',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='breakfast_price_adult',
            field=models.PositiveIntegerField(default=499),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='breakfast_price_child',
            field=models.PositiveIntegerField(default=349),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='policies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='refundable_deposit',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
