# Generated by Django 5.2.3 on 2026-01-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_app', '0004_booking_base_amount_booking_gst_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='gst_number',
            field=models.CharField(blank=True, help_text='Hotel GST Number', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='gst_percent',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
