# Generated by Django 5.2.3 on 2026-01-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_app', '0005_hotel_gst_number_hotel_gst_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='gst_number',
            field=models.CharField(blank=True, help_text='Hotel GSTIN Number', max_length=20),
        ),
    ]
