# Generated by Django 5.2.3 on 2026-01-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_app', '0008_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
