# Generated by Django 5.2.3 on 2026-01-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_app', '0010_alter_review_options_alter_review_rating_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('villa', 'Villa'), ('resort', 'Resort')], default='hotel', max_length=10),
        ),
    ]
