# Generated by Django 5.2.3 on 2026-01-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h_app', '0011_hotel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='category',
        ),
    ]
