# Generated by Django 5.2.3 on 2026-01-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_app', '0013_hotel_address_hotel_category_hotel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
