# Generated by Django 5.2.3 on 2026-01-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_app', '0014_hotel_city_alter_hotel_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
