# Generated by Django 5.2.3 on 2026-01-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_app', '0015_hotel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
