# Generated by Django 5.2.3 on 2026-03-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_app', '0021_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
