# Generated by Django 6.0.4 on 2026-04-25 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h_app', '0023_booking_discount_amount_booking_final_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
    ]
